
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    // App & Nav
    appTitle: "LinkW WMS",
    appSubtitle: "Warehouse Management System",
    dashboard: "Dashboard",
    rulesOps: "Location Arrangement",
    stockAdjustment: "Stock Adjustment",
    biSystem: "BI System",
    exceptionsTitle: "Exceptions",
    wms: "WMS Integration",
    userManagement: "User Management",
    locationManagement: "Location Management",
    cloudSync: "Cloud Sync",
    user: "User",
    signOut: "Sign Out",
    queryContainerHistory: "Query Container History",
    installApp: "Install App",
    installAppDesc: "Install LinkW on your home screen for quick access.",
    install: "Install",
    mobileStocktaking: "Mobile Stocktaking",
    
    // Cost Control
    costControl: "Cost Control",
    costDesc: "Manage expenses, assets, procurement and vendors.",
    tabProcurement: "Procurement",
    tabMaintenance: "Maintenance",
    tabAssets: "Assets",
    tabReimbursement: "Reimbursement",
    tabLedger: "Ledger",
    tabVendors: "Vendors",
    vendorRating: "Rating",
    vendorRatingReason: "Rating Reason",
    vendorType: "Service Type",
    assetOwner: "Responsibility",
    assetValue: "Value",
    maintenanceCost: "Repair Cost",
    totalExpenses: "Total Expenses",
    monthlyTrend: "Monthly Trend",
    breakdownByType: "Cost Breakdown",
    alertHighFreq: "Frequent Repairs!",
    alertHighCost: "Cost Exceeded Value!",
    requestNew: "New Request",
    approve: "Approve",
    reject: "Reject",
    
    // Dashboard Stats
    normalLoad: "Normal Load",
    emptyLoad: "Empty",
    lowLoad: "Low Load",
    modLoad: "Moderate Load",
    highLoad: "High Load",
    critLoad: "Critical Load",
    totalLocations: "Total Locations",
    zones: "Zones",
    palletCapacity: "Pallet Capacity",
    avgUtilization: "Avg Utilization",
    destConstraint: "Dest Constraint",
    locsExceeding: "Locations Exceeding Limit",
    zoneStats: "Zone Statistics",
    count: "Count",
    summaryByType: "Summary by Type",
    topDestinations: "Top Destinations",
    dest: "Dest",
    
    // Columns & Fields
    colRange: "Range",
    colDest: "Destination",
    colType: "Type",
    colMax: "Max",
    colCur: "Current",
    colCartons: "Cartons",
    colUtil: "Util",
    colAllow: "Allowed",
    colCurDest: "Cur Dest",
    colStatus: "Status",
    colNote: "Note",
    colActions: "Actions",
    colPhotos: "Photos",
    locationArrangement: "Location Arrangement",
    palletCount: "Pallet Count",
    
    // Common Actions
    add: "Add",
    cancel: "Cancel",
    done: "Done",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    confirmDelete: "Are you sure you want to delete this rule?",
    statusOverflow: "Overflow",
    statusOk: "OK",
    removeTag: "Remove tag",
    maxAllowed: "Max destinations allowed",
    current: "Current",
    search: "Search",
    close: "Close",
    
    // Dashboard Page
    overviewTitle: "Warehouse Overview",
    overviewDesc: "Real-time visualization of capacity and status.",
    editLayout: "Edit Layout",
    moveUp: "Move Up",
    moveDown: "Move Down",
    
    // Rules Page
    selectDestinations: "Select Destinations",
    searchPlaceholder: "Search...",
    manageTasks: "Manage Tasks",
    taskPlaceholder: "New task...",
    noTasks: "No tasks found.",
    manualUnload: "Manual Unload",
    rules: "Arrangement",
    inventory: "Inventory",
    importInventory: "Import Inventory",
    downloadData: "Download Data",
    unload: "Import Container Sheet",
    uploadFile: "Upload File",
    batchUpload: "Batch Upload",
    exportPlan: "Export Plan",
    exportPlanTooltip: "Export current unload plan to Excel",
    outbound: "Outbound",
    manualUnloadTitle: "Manual Unload Entry",
    containerNo: "Container No",
    addDestRow: "Add Destination Row",
    processUnload: "Process Unload",
    unloadSuccess: "Unload processed successfully.",
    history: "History",
    noHistory: "No history found for this location.",
    columnSettings: "Column Settings",
    locationExistsError: "Location {locationCode} already exists.",
    importSuccess: "Import successful.",
    batchImportSuccess: "Batch import successful. Processed {count} files, assigned {locations} locations.",
    duplicateContainerError: "Container {container} already exists.",
    deductedPallets: "Deducted pallets",
    priority: "Priority",
    pHigh: "High",
    pMedium: "Medium",
    pLow: "Low",
    
    // Mobile Stocktaking
    stocktakingTitle: "Inventory Count",
    scanLocation: "Scan Location",
    enterLocationCode: "Enter Location Code...",
    locationNotFound: "Location not found.",
    updateStock: "Update Stock",
    recentUpdates: "Recent Updates",
    updatedLocation: "Updated {location}",
    confirmUpdate: "Confirm Update",
    destinations: "Destinations",
    
    // WMS Page
    tabInventory: "Inventory",
    descInventory: "Manage stock levels",
    tabInbound: "Inbound",
    descInbound: "Process incoming shipments",
    tabOutbound: "Outbound",
    descOutbound: "Process outgoing orders",
    tabMaster: "Master Data",
    descMaster: "System configuration",
    wmsModule: "WMS Module",
    wmsIntegration: "Integration",
    noWmsUrl: "No WMS URL Configured",
    enterWmsUrl: "Enter the URL of your WMS system",
    loadWms: "Load WMS",
    
    // Login
    loginTitle: "Welcome Back",
    loginSubtitle: "Sign in to access your dashboard",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    invalidCredentials: "Invalid credentials",
    
    // Exceptions
    exceptionsDesc: "Log and track shipment anomalies and issues.",
    addException: "Add Exception",
    pcNo: "PC No",
    description: "Description",
    photos: "Photos",
    uploadPhoto: "Upload Photo",
    record: "Record Exception",
    exceptionAdded: "Exception recorded.",
    
    // Cloud Sync
    settingsSaved: "Settings saved.",
    urlRequired: "Server URL is required.",
    syncSuccess: "Synchronization successful.",
    syncError: "Synchronization failed.",
    cloudDesc: "Sync your data across devices.",
    pushToCloud: "Push to Cloud",
    pullFromCloud: "Pull from Cloud",
    lastSync: "Last Synced:",
    cloudSettings: "Connection Settings",
    serverUrl: "Server URL",
    apiKey: "API Key",
    
    // Assistant
    assistantTitle: "Warehouse Assistant",
    aiGreeting: "Hello! I'm Mike, your warehouse assistant. How can I help you today?",
    aiError: "Sorry, I encountered an error processing your request.",
    aiChatCleared: "Chat history cleared.",
    aiImageDesc: "Ask about this image...",
    assistantPlaceholder: "Ask me anything about the warehouse...",
    aiDisclaimer: "AI responses may vary. Always verify critical information.",
    
    // Users
    addUser: "Add User",
    manageUsersDesc: "Manage system access and roles.",
    role: "Role",
    confirmDeleteUser: "Are you sure you want to delete this user?",
    userExists: "User already exists.",
    cannotDeleteSelf: "You cannot delete your own account.",
    userAdded: "User added successfully.",
    userDeleted: "User deleted successfully.",
    operator: "Operator",
    staff: "Staff",
    stock_adj: "Stock Adjustment",
    bulk_cargo: "Bulk Cargo",
    
    // Locations
    locationManagementDesc: "Add or remove warehouse locations.",
    addNewLocation: "Add New Location",
    locationCodePlaceholder: "e.g., A55",
    addLocation: "Add Location",
    existingLocations: "Existing Locations",
    deleteLocation: "Delete Location",
    confirmDeleteLocation: "Are you sure you want to delete location {locationCode}?",
    locationAdded: "Location {locationCode} added.",
    locationDeleted: "Location {locationCode} deleted.",
    locationNotEmptyError: "Location {locationCode} is not empty.",
    
    // BI
    biTitle: "Business Intelligence",
    biDesc: "Analytics and performance metrics.",
    totalInventory: "Total Inventory",
    globalUtilization: "Global Utilization",
    occupiedLocations: "Occupied Locations",
    recentActivity: "Recent Activity",
    zonePerformance: "Zone Performance",
    inventoryComposition: "Inventory Composition",
    operationalActivity: "Operational Activity",
    capacityDistribution: "Capacity Distribution",
    
    // Stock Adjustment
    stockAdjustmentDesc: "Manage stock moves and optimizations.",
    manualExecution: "Field Execution",
    smartSuggestion: "Smart Suggestions",
    taskList: "Task List",
    showPendingTasks: "Show Pending Only",
    showAllTasks: "Show All",
    clearCompleted: "Clear Completed",
    taskStatus: "Status",
    taskLocation: "Location",
    taskContent: "Content",
    taskTime: "Created At",
    completed: "Completed",
    pending: "Pending",
    selectSource: "Select Source",
    available: "Available",
    maxQty: "Max Qty",
    moveQty: "Move Qty",
    selectTarget: "Select Target",
    moveDest: "Move Destination",
    selectReason: "Reason",
    reasonBlocking: "Blocking",
    reasonMixed: "Mixed SKU",
    reasonOutbound: "Outbound Prep",
    reasonInbound: "Inbound Consolidation",
    autoCreateTasks: "Auto-create tasks for operators",
    executeMove: "Execute Move",
    executionHistory: "Execution History",
    executionSuccess: "Move executed successfully.",
    movesGenerated: "{count} moves generated.",
    noMovesFound: "No optimization moves found.",
    generateMoves: "Generate Moves",
    applyAll: "Apply All",
    sourceLoc: "Source",
    targetLoc: "Target",
    moveReason: "Reason",
    potentialSavings: "Potential Locations Freed",
    tasksCreated: "Tasks created for operators.",
    sourceEmpty: "Source location does not have enough stock.",
    invalidMove: "Invalid move configuration.",
    other: "Other",
    specifyReason: "Specify reason...",
    suggestionHint: "Fix overflows & consolidate (<30%).",
    from: "From",
    to: "To",
    noMatchingSuggestions: "No suggestions match this priority filter.",
    noRecentMoves: "No recent moves.",
    pallets: "Pallets",
    unitPlts: "plts",
    space: "space",
    noMatches: "No matches",
    max: "Max",
    quantityError: "Quantity must be greater than 0",
    sameLocationError: "Source and Target cannot be the same",
    outdatedSuggestions: "Location rules changed, suggestions outdated.",
    sourceChanged: "Source stock changed, cannot execute.",
    suggestionExecuted: "Suggestion executed.",
    
    // Container History
    containerHistoryTitle: "Container History",
    searchContainer: "Search Container...",
    confirmDeleteContainer: "Delete all data for container {container}?",
    containerDetails: "Container Details",
    printReport: "Print Report",
    noContainerSelected: "Select a container to view details",
    total: "Total",
    noContainerFound: "No containers found.",
    enterContainerToSearch: "Enter container number to search.",
    containerDeleted: "Container deleted successfully.",
    time: "Time",
    
    // Types
    "amz-main-A": "Amazon Main (A)",
    "amz-main-BC": "Amazon Main (B/C)",
    "amz-buffer": "Amazon Buffer",
    "sehin": "Shein Zone",
    "private": "Private",
    "platform": "Platform",
    "express": "Express",
    "suspense": "Suspense/Transfer",
    "highvalue": "High Value",
  },
  zh: {
    // App & Nav
    appTitle: "LinkW 盈仓科技",
    appSubtitle: "仓库管理系统",
    dashboard: "仪表盘",
    rulesOps: "库位安排",
    stockAdjustment: "库存调整",
    biSystem: "BI 报表",
    exceptionsTitle: "异常记录",
    wms: "WMS 集成",
    userManagement: "用户管理",
    locationManagement: "库位管理",
    cloudSync: "云同步",
    user: "用户",
    signOut: "退出登录",
    queryContainerHistory: "查询柜号历史",
    installApp: "安装应用",
    installAppDesc: "安装 LinkW 到主屏幕，享受更流畅的体验。",
    install: "安装",
    mobileStocktaking: "手机盘库",
    
    // Cost Control
    costControl: "内部管理",
    costDesc: "管理费用、设备资产、采购及供应商。",
    tabProcurement: "采购管理",
    tabMaintenance: "维修保养",
    tabAssets: "设备资产",
    tabReimbursement: "报销管理",
    tabLedger: "费用台账",
    tabVendors: "供应商",
    vendorRating: "评级",
    vendorRatingReason: "评级原因",
    vendorType: "服务类型",
    assetOwner: "责任人",
    assetValue: "原值",
    maintenanceCost: "维修费用",
    totalExpenses: "总费用",
    monthlyTrend: "月度趋势",
    breakdownByType: "费用构成",
    alertHighFreq: "频繁维修!",
    alertHighCost: "维修超限!",
    requestNew: "发起申请",
    approve: "批准",
    reject: "驳回",
    
    // Dashboard Stats
    normalLoad: "正常负载",
    emptyLoad: "空闲",
    lowLoad: "低负载",
    modLoad: "中等负载",
    highLoad: "高负载",
    critLoad: "严重负载",
    totalLocations: "总库位数",
    zones: "区域",
    palletCapacity: "托盘容量",
    avgUtilization: "平均利用率",
    destConstraint: "目的地限制",
    locsExceeding: "超限库位",
    zoneStats: "区域统计",
    count: "数量",
    summaryByType: "类型汇总",
    topDestinations: "热门目的地",
    dest: "目的地",
    
    // Columns & Fields
    colRange: "库位号",
    colDest: "目的地",
    colType: "类型",
    colMax: "最大",
    colCur: "当前",
    colCartons: "箱数",
    colUtil: "利用率",
    colAllow: "允许数",
    colCurDest: "当前数",
    colStatus: "状态",
    colNote: "备注",
    colActions: "操作",
    colPhotos: "照片",
    locationArrangement: "库位安排",
    palletCount: "板数",
    
    // Common Actions
    add: "添加",
    cancel: "取消",
    done: "完成",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    confirmDelete: "确定要删除此规则吗？",
    statusOverflow: "超限",
    statusOk: "正常",
    removeTag: "移除标签",
    maxAllowed: "允许的最大目的地数",
    current: "当前",
    search: "搜索",
    close: "关闭",
    
    // Dashboard Page
    overviewTitle: "仓库概览",
    overviewDesc: "仓库容量和状态的实时可视化。",
    editLayout: "编辑布局",
    moveUp: "上移",
    moveDown: "下移",
    
    // Rules Page
    selectDestinations: "选择目的地",
    searchPlaceholder: "搜索...",
    manageTasks: "管理任务",
    taskPlaceholder: "新任务...",
    noTasks: "暂无任务。",
    manualUnload: "人工录入",
    rules: "库位安排",
    inventory: "库存",
    importInventory: "导入库存",
    downloadData: "下载数据",
    unload: "导入拆柜单",
    uploadFile: "上传文件",
    batchUpload: "批量上传",
    exportPlan: "导出方案",
    exportPlanTooltip: "导出当前卸货方案为Excel",
    outbound: "出库",
    manualUnloadTitle: "人工录入",
    containerNo: "柜号",
    addDestRow: "添加目的地行",
    processUnload: "处理卸货",
    unloadSuccess: "卸货处理成功。",
    history: "历史记录",
    noHistory: "该库位无历史记录。",
    columnSettings: "列设置",
    locationExistsError: "库位 {locationCode} 已存在。",
    importSuccess: "导入成功。",
    batchImportSuccess: "批量导入成功。处理了 {count} 个文件，分配了 {locations} 个库位。",
    duplicateContainerError: "柜号 {container} 已存在。",
    deductedPallets: "已扣减托盘",
    priority: "优先级",
    pHigh: "高",
    pMedium: "中",
    pLow: "低",
    
    // Mobile Stocktaking
    stocktakingTitle: "库存盘点",
    scanLocation: "扫描库位",
    enterLocationCode: "输入库位号...",
    locationNotFound: "未找到库位。",
    updateStock: "更新库存",
    recentUpdates: "近期更新",
    updatedLocation: "已更新 {location}",
    confirmUpdate: "确认更新",
    destinations: "目的地",
    
    // WMS Page
    tabInventory: "库存",
    descInventory: "管理库存水平",
    tabInbound: "入库",
    descInbound: "处理入库货件",
    tabOutbound: "出库",
    descOutbound: "处理出库订单",
    tabMaster: "基础数据",
    descMaster: "系统配置",
    wmsModule: "WMS 模块",
    wmsIntegration: "集成",
    noWmsUrl: "未配置 WMS URL",
    enterWmsUrl: "输入您的 WMS 系统 URL",
    loadWms: "加载 WMS",
    
    // Login
    loginTitle: "欢迎回来",
    loginSubtitle: "登录以访问您的仪表盘",
    username: "用户名",
    password: "密码",
    signIn: "登录",
    invalidCredentials: "凭证无效",
    
    // Exceptions
    exceptionsDesc: "记录和追踪货件异常。",
    addException: "添加异常",
    pcNo: "PC号",
    description: "描述",
    photos: "照片",
    uploadPhoto: "上传照片",
    record: "记录异常",
    exceptionAdded: "异常已记录。",
    
    // Cloud Sync
    settingsSaved: "设置已保存。",
    urlRequired: "服务器 URL 必填。",
    syncSuccess: "同步成功。",
    syncError: "同步失败。",
    cloudDesc: "在多台设备间同步数据。",
    pushToCloud: "推送到云端",
    pullFromCloud: "从云端拉取",
    lastSync: "上次同步：",
    cloudSettings: "连接设置",
    serverUrl: "服务器 URL",
    apiKey: "API Key",
    
    // Assistant
    assistantTitle: "仓库助手",
    aiGreeting: "你好！我是 Mike，你的仓库助手。今天有什么可以帮你的吗？",
    aiError: "抱歉，处理您的请求时出错。",
    aiChatCleared: "聊天记录已清除。",
    aiImageDesc: "询问关于这张图片...",
    assistantPlaceholder: "询问任何关于仓库的问题...",
    aiDisclaimer: "AI 回复可能有所不同。请务必核实关键信息。",
    
    // Users
    addUser: "添加用户",
    manageUsersDesc: "管理系统访问权限和角色。",
    role: "角色",
    confirmDeleteUser: "确定要删除此用户吗？",
    userExists: "User already exists.",
    cannotDeleteSelf: "无法删除您自己的帐户。",
    userAdded: "User added successfully.",
    userDeleted: "User deleted successfully.",
    operator: "操作员",
    staff: "员工",
    stock_adj: "库存调整",
    bulk_cargo: "大货",
    
    // Locations
    locationManagementDesc: "添加或移除仓库库位。",
    addNewLocation: "添加新库位",
    locationCodePlaceholder: "例如：A55",
    addLocation: "添加库位",
    existingLocations: "现有库位",
    deleteLocation: "删除库位",
    confirmDeleteLocation: "确定要删除库位 {locationCode} 吗？",
    locationAdded: "库位 {locationCode} 已添加。",
    locationDeleted: "库位 {locationCode} 已删除。",
    locationNotEmptyError: "库位 {locationCode} 不为空。",
    
    // BI
    biTitle: "商业智能",
    biDesc: "分析和绩效指标。",
    totalInventory: "总库存",
    globalUtilization: "全局利用率",
    occupiedLocations: "占用库位",
    recentActivity: "近期活动",
    zonePerformance: "区域绩效",
    inventoryComposition: "库存构成",
    operationalActivity: "运营活动",
    capacityDistribution: "容量分布",
    
    // Stock Adjustment
    stockAdjustmentDesc: "管理库存移动和优化。",
    manualExecution: "手动移库",
    smartSuggestion: "智能建议",
    taskList: "任务列表",
    showPendingTasks: "仅显示待处理",
    showAllTasks: "显示全部",
    clearCompleted: "清除已完成",
    taskStatus: "状态",
    taskLocation: "库位",
    taskContent: "内容",
    taskTime: "创建时间",
    completed: "已完成",
    pending: "待处理",
    selectSource: "选择来源",
    available: "可用",
    maxQty: "最大数量",
    moveQty: "移动数量",
    selectTarget: "选择目标",
    moveDest: "移动目的地",
    selectReason: "原因",
    reasonBlocking: "阻挡",
    reasonMixed: "混货整理",
    reasonOutbound: "备货出库",
    reasonInbound: "入库合并",
    autoCreateTasks: "自动生成操作员任务",
    executeMove: "执行移动",
    executionHistory: "执行历史",
    executionSuccess: "移动执行成功。",
    movesGenerated: "生成了 {count} 条建议。",
    noMovesFound: "未找到移动建议。",
    generateMoves: "生成建议",
    applyAll: "应用全部",
    sourceLoc: "来源",
    targetLoc: "目标",
    moveReason: "原因",
    potentialSavings: "预计腾空库位",
    tasksCreated: "已生成操作员任务单。",
    sourceEmpty: "来源库位库存不足。",
    invalidMove: "无效的移动配置。",
    other: "其他",
    specifyReason: "请输入原因...",
    suggestionHint: "修复超限及合并零散库存 (<30%)。",
    from: "从",
    to: "到",
    noMatchingSuggestions: "没有符合当前优先级的建议。",
    noRecentMoves: "暂无近期移动记录。",
    pallets: "托盘",
    unitPlts: "板",
    space: "空位",
    noMatches: "无匹配",
    max: "最大",
    quantityError: "数量必须大于 0",
    sameLocationError: "来源和目标库位不能相同",
    outdatedSuggestions: "库位规则已变更，建议已过期。",
    sourceChanged: "来源库存已变更，无法执行。",
    suggestionExecuted: "建议已执行。",
    
    // Container History
    containerHistoryTitle: "柜号历史",
    searchContainer: "搜索柜号...",
    confirmDeleteContainer: "确定要删除柜号 {container} 的所有数据吗？",
    containerDetails: "柜号详情",
    printReport: "打印报告",
    noContainerSelected: "选择一个柜号查看详情",
    total: "总计",
    noContainerFound: "未找到柜号。",
    enterContainerToSearch: "输入柜号开始搜索。",
    containerDeleted: "柜号删除成功。",
    time: "时间",
    
    // Types
    "amz-main-A": "亚马逊主区 (A)",
    "amz-main-BC": "亚马逊主区 (B/C)",
    "amz-buffer": "亚马逊偏仓",
    "sehin": "希音专区",
    "private": "私人地址",
    "platform": "平台类",
    "express": "快递区",
    "suspense": "暂扣/中转",
    "highvalue": "High Value",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
